### PR TITLE
Add support for lookbehinds

### PR DESCRIPTION
**Pull request by adrianheine**
See https://github.com/tc39/proposal-regexp-lookbehind.

### CODE REVIEW

**Comment by jviereck** [comment]
Thx @adrianheine for the PR. Can you update the `README.md` as well to show the `lookbehind` exists?

**Comment by adrianheine** [comment]
Sure, done that and also updated the AST documentation.

**Comment by jviereck** [comment]
Thanks!

**Comment by ewanharris** [comment]
@jviereck Hey there, is it possible for this to be published to npm? It looks like this hasn't been published yet? Thanks!

**Comment by jviereck** [comment]
@ewanharris, thanks - I just published v0.4.0 to npm. Let me know if there is anything else.

**Pull request merged**
