### PR TITLE
Detect lone or unescaped brackets and braces when the unicode flag is set

### PR DESCRIPTION
**Pull request by pygy**
Hi @jviereck 

This fixes https://github.com/mathiasbynens/regexpu-core/issues/36 and thus https://github.com/babel/babel/issues/11138

Edit: force push for code styling reasons.

### CODE REVIEW

**Comment by pygy** [comment]
Actually, wait... This will cause a Regexpocalypse that will not be easy to fix once this is live (because a codemod would rely on Babel, which would catch the update automatically because the way both Babel and regexpu-core rely on semver).

**Comment by nicolo-ribaudo** [comment]
I don't think that the situation is as tragic as you picture it, for a few reasons:
1. This is an edge case.
2. This is a normal bug: if someone relies on the buggy behavior, the burden of avoiding breakages is on them. Otherwise, every bugfix should be considered a breaking change.
3. This package already had some bugfixes which caused more errors, like https://github.com/jviereck/regjsparser/pull/91, and no one complained
4. When people will stop transpiling `/u` (hopefully soon, since it's supported by every browser version with `> 1.5%` market share), their code will be broken regardless of this PR.

**Comment by pygy** [comment]
Let's roll with it then :-)

**Comment by jviereck** [comment]
Thanks @pygy for providing this!

I agree with the arguments outlined by @nicolo-ribaudo and therefore accepted this PR.

**Comment by jviereck** [comment]
Published new release to npm as v0.6.3 - https://www.npmjs.com/package/regjsparser/v/0.6.3.

Thanks once again @pygy !

**Comment by jens-duttke** [comment]
Please see issue #101 . This change introduced a bug.

**Comment by jviereck** [comment]
Thanks for reporting this. I most likely have some time over the weekend to look into this.

@nicolo-ribaudo, @pygy, @jens-duttke  Do you think it's better in the meantime to make a new release with the change removed for now?

**Comment by nicolo-ribaudo** [comment]
I think that it's ok to wait a few days. If you end up not having time to fix it please ping me!

**Comment by jviereck** [comment]
Digging into this, when reading the JS RegExp gramma, I am not sure why `/}/u` is supposed to be rejected. That is, I think this should parse as:

```
...
Atom
PatternCharacter
SourceCharacter
```
But `SourceCharacter` has no quantification on the unicode `u` flag. See the documentation here:

  https://www.ecma-international.org/ecma-262/10.0/index.html#prod-PatternCharacter

Can someone give me a pointer what I am missing here?

Once it's clear to me why `/}/u` is supposed to be rejected, I hope to be able to fix the regression in #101 .

**Comment by nicolo-ribaudo** [comment]
I'm reading the spec, but I have never read the regexp section before :sweat_smile: 

cc @mathiasbynens Maybe you know why?

**Pull request merged**
