### PR TITLE
Minor, updated the README.md docs to show how to use the two features

### PR DESCRIPTION
**Pull request by jviereck**
Minor, updated the README.md docs to show how to use the two features (`unicodePropertyEscape` and `namedGroups`).

I also went over the changes in #83 and #84. To my believe all open followup points are adressed. If I don't hear a veto, I am going to create a new release after this PR lands.

\review: @mathiasbynens, @nicolo-ribaudo  ?

### CODE REVIEW

**Comment by jviereck** [comment]
Old versions of node seem to fail on Travis CI. Does someone has strong opinions about supporting these old versions? I lean towards not support them.

screen shot 2018-01-04 at 10 40 19 am

**Comment by nicolo-ribaudo** [comment]
Oh travis is failing because I had to use `String.fromCodePoint` (https://github.com/jviereck/regjsparser/blob/gh-pages/parser.js#L807).
If you want to support old node versions, you could add a fallback implementation.

Anyway, just don't drop node >= 4 since Babel (which depends on this package) supports them :stuck_out_tongue:

**Comment by jviereck** [comment]
> Oh travis is failing because I had to use String.fromCodePoint (https://github.com/jviereck/regjsparser/blob/gh-pages/parser.js#L807).

Can the calls be replaced by `String.fromCharCode`? If not, is there a common npm style for adding polyfill code?

**Comment by nicolo-ribaudo** [comment]
We can't replace it, because it wont work for `\u{xxxxx}`, where `xxxxx > 0xffff`. I'm working on a PR to fix it.

**Comment by jviereck** [comment]
Builds clean now after #86 has landed :)

**Comment by nicolo-ribaudo** [comment]
@jviereck Could you create a new release? It's needed for https://github.com/mathiasbynens/regexpu-core/pull/14

**Comment by jviereck** [comment]
> @jviereck Could you create a new release? It's needed for mathiasbynens/regexpu-core#14

Released version `0.3.0` with the latest changes.

**Pull request merged**
