### PR TITLE
Fix parsing of group references in unicode mode

### LINKED ISSUE #121: Regression: `(a)\1` throws when parsed with the `u` flag
```js
parse("(a)\\1", "u")
```
throws, but it's a valid regex.

This regression was probably introduced by #115; I'm working on a fix.

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
Fixes #121

cc @JLHwung

### CODE REVIEW

**Comment by jviereck** [comment]
hi @nicolo-ribaudo, thanks for providing a fix to #121. This looks good!

There is a conflict with the file `test/test-data-unicode-set.json`. Can you resolve the conflict? Then I would merge the PR.

**Comment by nicolo-ribaudo** [comment]
Done!

**Comment by jviereck** [comment]
Great! Published version 0.8.2 to npm.

**Comment by nicolo-ribaudo** [comment]
Thanks :smile:

**Pull request merged**
